'use server';
/**
 * @fileOverview A Genkit flow for transforming a portrait into a Ghibli-style AI traveler illustration.
 *
 * - transformPortrait - A function that handles the image-to-image transformation process.
 * - TransformPortraitInput - The input type for the transformPortrait function.
 * - TransformPortraitOutput - The return type for the transformPortrait function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const TransformPortraitInputSchema = z.object({
  photoDataUri: z.string().describe("A photo of a person, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type TransformPortraitInput = z.infer<typeof TransformPortraitInputSchema>;

const TransformPortraitOutputSchema = z.object({
  imageUrl: z.string().describe("The generated image as a data URI."),
});
export type TransformPortraitOutput = z.infer<typeof TransformPortraitOutputSchema>;

export async function transformPortrait(input: TransformPortraitInput): Promise<TransformPortraitOutput> {
  const { media } = await ai.generate({
    model: 'googleai/gemini-2.5-flash-image',
    prompt: [
      { media: { url: input.photoDataUri } },
      { text: 'Transform this person into a cool AI traveler geek in Studio Ghibli art style. The backdrop should be a futuristic, high-tech, AI-integrated San Francisco featuring the Golden Gate Bridge in a whimsical, hand-painted aesthetic. The character should look like a savvy traveler with cool gadgets. Capture the person\'s likeness but stylize it in the iconic Ghibli anime style with soft colors and detailed backgrounds.' },
    ],
    config: {
      responseModalities: ['TEXT', 'IMAGE'],
    },
  });

  if (!media || !media.url) {
    throw new Error('No image was generated by the model.');
  }

  return { imageUrl: media.url };
}
